const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
    getDashboardStats: (filter) => ipcRenderer.invoke('get-dashboard-stats', filter),
    getTherapistStats: (filter) => ipcRenderer.invoke('get-therapist-stats', filter),
    getTopCustomers: () => ipcRenderer.invoke('get-top-customers'),
    getRevenueTrend: () => ipcRenderer.invoke('get-revenue-trend'),
    getServiceBreakdown: () => ipcRenderer.invoke('get-service-breakdown'),
    getPaymentBreakdown: () => ipcRenderer.invoke('get-payment-breakdown'),
    getExpenseRevenueComparison: () => ipcRenderer.invoke('get-expense-revenue-comparison'),
    getDailyVisits: () => ipcRenderer.invoke('get-daily-visits'),
    getTherapists: () => ipcRenderer.invoke('get-therapists'),
    addVisit: (data) => ipcRenderer.invoke('add-visit', data),
    getVisits: (page = 1, limit = 10, searchQuery = '') => ipcRenderer.invoke('get-visits', page, limit, searchQuery),
    deleteVisit: (id) => ipcRenderer.invoke('delete-visit', id),
    updateVisit: (data) => ipcRenderer.invoke('update-visit', data),
    getEnquiries: (page = 1, limit = 10, searchQuery = '') => ipcRenderer.invoke('get-enquiries', page, limit, searchQuery),
    addEnquiry: (data) => ipcRenderer.invoke('add-enquiry', data),
    updateEnquiry: (data) => ipcRenderer.invoke('update-enquiry', data),
    deleteEnquiry: (id) => ipcRenderer.invoke('delete-enquiry', id),
    getCalls: (page = 1, limit = 10, searchQuery = '', statusFilter = '') => ipcRenderer.invoke('get-calls', page, limit, searchQuery, statusFilter),
    addCall: (data) => ipcRenderer.invoke('add-call', data),
    updateCall: (data) => ipcRenderer.invoke('update-call', data),
    deleteCall: (id) => ipcRenderer.invoke('delete-call', id),
    getExpenses: (page = 1, limit = 10, searchQuery = '') => ipcRenderer.invoke('get-expenses', page, limit, searchQuery),
    addExpense: (data) => ipcRenderer.invoke('add-expense', data),
    updateExpense: (data) => ipcRenderer.invoke('update-expense', data),
    deleteExpense: (id) => ipcRenderer.invoke('delete-expense', id),
    getExpenseSummary: () => ipcRenderer.invoke('get-expense-summary'),

    // Smart Recall data sources
    getSmartRecall: (days = 30) => ipcRenderer.invoke('get-smart-recall', days), // visits
    getSmartRecallCalls: (days = 30) => ipcRenderer.invoke('get-smart-recall-calls', days),
    getSmartRecallEnquiries: (days = 30) => ipcRenderer.invoke('get-smart-recall-enquiries', days),
    searchCustomers: (query) => ipcRenderer.invoke('search-customers', query),
    searchCustomersLive: (query) => ipcRenderer.invoke('search-customers-live', query),
    getCustomerDetails: (id) => ipcRenderer.invoke('get-customer-details', id),
    getCustomerCalls: (phone) => ipcRenderer.invoke('get-customer-calls', phone),
    mergeCustomers: (primaryId, targetId) => ipcRenderer.invoke('merge-customers', primaryId, targetId),
    exportAllCustomers: () => ipcRenderer.invoke('export-all-customers'),
});
